In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import os

In [4]:
path="/mnt/c/Users/isabe/OneDrive/Desktop/Lavoro/Tuscia/chiara/peaks_background/bufale_isa/"
os.chdir(path)

In [5]:
mandria_path = './dati_bufale/dati_maggio_giugno/protocollo_2/ch4_clean_out_neg_bg_10_maggio_tagliato.csv'
mandria = pd.read_csv(mandria_path)

In [6]:
mandria['ID_animal'] = mandria['ID_animal'].apply(lambda x: int(x))
mandria['Milking_number'] = mandria['Milking_number'].apply(lambda x: int(x))

In [7]:
#dividing and plotting each milking (keeping animal information)
#inspection of milking with calculus of mean, median, standard deviation without removal of data

animals = list(set(mandria['ID_animal']))
mungiture = list(set(mandria['Milking_number']))
print(len(animals))
print(len(mungiture))

matrix=[]

mandria_cutted=mandria

35
50

In [8]:
mandria_cutted.tail()

,timestamp,CH4,date,Ora inizio,Produzione (kg),ID_animal,Milking_duration,Milking_number,progressive_seconds
24069,2024-05-16 12:16:59.851355,71.57,2024-05-16,2024-05-16 12:12:52,2.32,6922,5.38,50,495
24070,2024-05-16 12:17:00.352547,66.27,2024-05-16,2024-05-16 12:12:52,2.32,6922,5.38,50,496
24071,2024-05-16 12:17:00.853980,55.27,2024-05-16,2024-05-16 12:12:52,2.32,6922,5.38,50,497
24072,2024-05-16 12:17:01.355188,45.27,2024-05-16,2024-05-16 12:12:52,2.32,6922,5.38,50,498
24073,2024-05-16 12:17:01.856484,24.87,2024-05-16,2024-05-16 12:12:52,2.32,6922,5.38,50,499

In [9]:
# Convert 'milking_duration' to seconds
mandria_cutted['Milking_duration'] = mandria_cutted['Milking_duration'].apply(lambda x: str(x))
mandria_cutted['milking_duration_seconds'] = mandria_cutted['Milking_duration'].apply(lambda x: int(x.split('.')[0]) * 60 + int(x.split('.')[1]))

In [10]:
print(mandria_cutted.tail())
print(mandria_cutted.shape)
print(len(set(mandria_cutted['Milking_number'])))

                        timestamp    CH4        date           Ora inizio  \
24069  2024-05-16 12:16:59.851355  71.57  2024-05-16  2024-05-16 12:12:52
24070  2024-05-16 12:17:00.352547  66.27  2024-05-16  2024-05-16 12:12:52
24071  2024-05-16 12:17:00.853980  55.27  2024-05-16  2024-05-16 12:12:52
24072  2024-05-16 12:17:01.355188  45.27  2024-05-16  2024-05-16 12:12:52
24073  2024-05-16 12:17:01.856484  24.87  2024-05-16  2024-05-16 12:12:52

       Produzione (kg)  ID_animal Milking_duration  Milking_number  \
24069             2.32       6922             5.38              50
24070             2.32       6922             5.38              50
24071             2.32       6922             5.38              50
24072             2.32       6922             5.38              50
24073             2.32       6922             5.38              50

       progressive_seconds  milking_duration_seconds
24069                  495                       338
24070                  496                       338
24071                  497                       338
24072                  498                       338
24073                  499                       338
(24074, 10)
50

In [11]:
# Filter the DataFrame to keep only milking records of 3 minutes (180+60 seconds)
mandria_cutted = mandria_cutted[mandria_cutted['milking_duration_seconds']>=240].reset_index(drop=True)

In [12]:
print(mandria_cutted.tail())
print(mandria_cutted.shape)
print(len(set(mandria_cutted['Milking_number'])))

                        timestamp    CH4        date           Ora inizio  \
24069  2024-05-16 12:16:59.851355  71.57  2024-05-16  2024-05-16 12:12:52
24070  2024-05-16 12:17:00.352547  66.27  2024-05-16  2024-05-16 12:12:52
24071  2024-05-16 12:17:00.853980  55.27  2024-05-16  2024-05-16 12:12:52
24072  2024-05-16 12:17:01.355188  45.27  2024-05-16  2024-05-16 12:12:52
24073  2024-05-16 12:17:01.856484  24.87  2024-05-16  2024-05-16 12:12:52

       Produzione (kg)  ID_animal Milking_duration  Milking_number  \
24069             2.32       6922             5.38              50
24070             2.32       6922             5.38              50
24071             2.32       6922             5.38              50
24072             2.32       6922             5.38              50
24073             2.32       6922             5.38              50

       progressive_seconds  milking_duration_seconds
24069                  495                       338
24070                  496                       338
24071                  497                       338
24072                  498                       338
24073                  499                       338
(24074, 10)
50

In [12]:
#Check per mungiture < 240 secondi 

# milk_sbagliata = mandria_cutted.loc[mandria_cutted['milking_duration_seconds']<240]
# milk_sbagliata.shape

(0, 9)

In [137]:
# Assign a progressive number of seconds starting from 1 within each milking session
mandria_cutted['progressive_seconds'] = mandria_cutted.groupby(['ID_animal', 'Milking_number']).cumcount() + 1

In [13]:
print(mandria_cutted.tail())

                        timestamp    CH4        date           Ora inizio  \
24069  2024-05-16 12:16:59.851355  71.57  2024-05-16  2024-05-16 12:12:52
24070  2024-05-16 12:17:00.352547  66.27  2024-05-16  2024-05-16 12:12:52
24071  2024-05-16 12:17:00.853980  55.27  2024-05-16  2024-05-16 12:12:52
24072  2024-05-16 12:17:01.355188  45.27  2024-05-16  2024-05-16 12:12:52
24073  2024-05-16 12:17:01.856484  24.87  2024-05-16  2024-05-16 12:12:52

       Produzione (kg)  ID_animal Milking_duration  Milking_number  \
24069             2.32       6922             5.38              50
24070             2.32       6922             5.38              50
24071             2.32       6922             5.38              50
24072             2.32       6922             5.38              50
24073             2.32       6922             5.38              50

       progressive_seconds  milking_duration_seconds
24069                  495                       338
24070                  496                       338
24071                  497                       338
24072                  498                       338
24073                  499                       338

In [139]:
mandria_cutted.tail

<bound method NDFrame.tail of                           timestamp     CH4        date           Ora inizio  \
0        2024-05-15 22:48:06.498279   56.05  2024-05-15  2024-05-15 22:48:06
1        2024-05-15 22:48:07.000104   55.85  2024-05-15  2024-05-15 22:48:06
2        2024-05-15 22:48:07.501497   58.15  2024-05-15  2024-05-15 22:48:06
3        2024-05-15 22:48:08.002406   60.75  2024-05-15  2024-05-15 22:48:06
4        2024-05-15 22:48:08.503446   63.15  2024-05-15  2024-05-15 22:48:06
...                             ...     ...         ...                  ...
1176812  2024-06-14 12:16:41.782150  159.35  2024-06-14  2024-06-14 12:09:48
1176813  2024-06-14 12:16:42.785144  144.65  2024-06-14  2024-06-14 12:09:48
1176814  2024-06-14 12:16:43.787620  216.55  2024-06-14  2024-06-14 12:09:48
1176815  2024-06-14 12:16:44.790575  263.85  2024-06-14  2024-06-14 12:09:48
1176816  2024-06-14 12:16:45.791937  328.05  2024-06-14  2024-06-14 12:09:48

         Produzione (kg)  ID_animal Milking_duration  Milking_number  \
0                   1.79       5983             8.15               1
1                   1.79       5983             8.15               1
2                   1.79       5983             8.15               1
3                   1.79       5983             8.15               1
4                   1.79       5983             8.15               1
...                  ...        ...              ...             ...
1176812             5.10     245606              9.2            2502
1176813             5.10     245606              9.2            2502
1176814             5.10     245606              9.2            2502
1176815             5.10     245606              9.2            2502
1176816             5.10     245606              9.2            2502

         milking_duration_seconds  progressive_seconds
0                             495                    1
1                             495                    2
2                             495                    3
3                             495                    4
4                             495                    5
...                           ...                  ...
1176812                       542                  409
1176813                       542                  410
1176814                       542                  411
1176815                       542                  412
1176816                       542                  413

[1176817 rows x 10 columns]>

In [140]:
# Remove rows where 'progressive_seconds' is less than 60 (tolgo primo minuto di records)
filtered_df = mandria_cutted[mandria_cutted['progressive_seconds'] > 60].reset_index(drop=True)

In [142]:
filtered_df.tail()
print(filtered_df.shape)
print(len(set(filtered_df['Milking_number'])))

(1026757, 10)
2501

In [143]:
#taglio a 4 minuti per mungitura (240+60=300)
filtered_df2 = filtered_df[filtered_df['progressive_seconds'] <= 300].reset_index(drop=True)

In [145]:
print(filtered_df2.shape)
print(len(set(filtered_df2['Milking_number'])))

(597041, 10)
2501

In [149]:
filtered_df2[filtered_df2['Milking_number'] == 2].tail()

,timestamp,CH4,date,Ora inizio,Produzione (kg),ID_animal,Milking_duration,Milking_number,milking_duration_seconds,progressive_seconds
475,2024-05-15 22:59:34.249837,160.53,2024-05-15,2024-05-15 22:57:06,3.5,245578,7.2,2,422,296
476,2024-05-15 22:59:34.751061,153.13,2024-05-15,2024-05-15 22:57:06,3.5,245578,7.2,2,422,297
477,2024-05-15 22:59:35.252368,151.93,2024-05-15,2024-05-15 22:57:06,3.5,245578,7.2,2,422,298
478,2024-05-15 22:59:35.753313,161.73,2024-05-15,2024-05-15 22:57:06,3.5,245578,7.2,2,422,299
479,2024-05-15 22:59:36.254295,186.23,2024-05-15,2024-05-15 22:57:06,3.5,245578,7.2,2,422,300

In [126]:
filtered_df2.loc[15100:15110]

,timestamp,CH4,date,Ora inizio,Produzione (kg),ID_animal,Milking_duration,Milking_number,milking_duration_seconds,progressive_seconds
15100,2024-07-02 04:31:04.029999,30.02,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,288
15101,2024-07-02 04:31:05.032233,30.92,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,289
15102,2024-07-02 04:31:06.034679,32.42,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,290
15103,2024-07-02 04:31:07.037347,28.32,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,291
15104,2024-07-02 04:31:08.039513,41.22,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,292
15105,2024-07-02 04:31:09.040916,40.42,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,293
15106,2024-07-02 04:31:10.042680,29.22,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,294
15107,2024-07-02 04:31:11.045940,21.62,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,295
15108,2024-07-02 04:31:12.048004,25.22,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,296
15109,2024-07-02 04:31:13.049661,1.02,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,297
15110,2024-07-02 04:31:14.051157,9.72,2024-07-02,2024-07-02 04:26:00,4.88,245575,5.36,63,336,298

In [23]:
ch4_mean = filtered_df2['CH4'].mean()

In [24]:
print("Mean of this month after cut is: ", ch4_mean)

Mean of this month after cut is:  79.48692774654097

In [150]:
# Salva il DataFrame combinato in un nuovo file CSV.
output_file = './dati_bufale/dati_maggio_giugno/protocollo_2/ch4_cutted_milkings'
filtered_df2.to_csv(output_file, index=False)