In [ ]:
#CHECK having all data without void

In [1]:
import pandas as pd
from datetime import datetime
import os

In [2]:
path="/mnt/c/Users/isabe/OneDrive/Desktop/Lavoro/Tuscia/chiara/peaks_background/bufale_isa/"
os.chdir(path)

In [5]:
week_1 = "./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/1Settimana_agosto_bufale-08012024000000-08082024235900.csv"
week_2 = "./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/2settimana_agosto_rinna-08092024000000-08162024235900.csv"
week_3 = "./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/3settimana_agosto_rinna-08162024000000-08232024235900.csv"
week_4 = "./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/4_settimana_agosto_rinna-08232024000000-08312024235900.csv"

In [6]:
df_1 = pd.read_csv(week_1, skiprows=1)
df_2 = pd.read_csv(week_2, skiprows=1)
df_3 = pd.read_csv(week_3, skiprows=1)
df_4 = pd.read_csv(week_4, skiprows=1)

/tmp/ipykernel_607/1127712242.py:2: DtypeWarning: Columns (1,2,3,4,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2 = pd.read_csv(week_2, skiprows=1)
/tmp/ipykernel_607/1127712242.py:3: DtypeWarning: Columns (1,2,3,4,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_3 = pd.read_csv(week_3, skiprows=1)
/tmp/ipykernel_607/1127712242.py:4: DtypeWarning: Columns (1,2,3,4,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_4 = pd.read_csv(week_4, skiprows=1)

In [8]:
df_4.tail()

,timestamp,CH4,CH4-mgm3,CO2,CO2-mgm3,FLOW,H-AIR,P,T-AIR,T-BOX
638932,08/30/2024 08:20:42.685681,91.3,59.896,969.1,1741.869,0.619,43.173,1004.007,35.096,35.727
638933,08/30/2024 08:20:43.688536,82.9,54.385,929.1,1672.388,0.829,43.167,1004.023,35.097,35.727
638934,08/30/2024 08:20:44.691011,75.1,49.268,873.3,1571.948,1.007,43.167,1004.012,35.097,35.727
638935,08/30/2024 08:20:45.693816,71.0,46.579,836.3,1505.348,1.221,43.167,1004.003,35.098,35.727
638936,08/30/2024 08:20:46.695530,64.4,42.249,819.5,1475.107,0.695,43.161,1004.042,35.099,35.737

In [8]:
timestamp = pd.DataFrame(df_1['timestamp'])
timestamp.head()
#print(timestamp.loc[101050:101100])

                    timestamp
0  08/01/2024 09:25:28.260847
1  08/01/2024 09:25:29.263544
2  08/01/2024 09:25:30.265996
3  08/01/2024 09:25:31.268802
4  08/01/2024 09:25:32.271264

In [ ]:
#CHECK BUCHI NEI DATI per giorno e ora, tentativo

In [ ]:
days = list()
hours = list()
for index, row in timestamp.iterrows():
    row = pd.DataFrame(row)
    string = row.iloc[0,0]
    string = string.split(".")[0]
    date = datetime.strptime(string, "%m/%d/%Y  %H:%M:%S")
    day = date.day
    hour = date.hour
    if day not in days:
        days.append(day)
    elif hour not in hours:
        hours.append(hour)
        print(hour)
    elif day != days[-1]:
        hours = list()
    #print(date.day)

days = set(days)
print(days)

In [ ]:
days = list()
for index, row in timestamp.iterrows():
    row = pd.DataFrame(row)
    string = row.iloc[0,0]
    string = string.split(".")[0]
    date = datetime.strptime(string, "%m/%d/%Y  %H:%M:%S")
    days.append(date.day)
    #print(date.day)

days = set(days)
print(days)

In [ ]:
'''
Agosto giorni assenti nei dati:
week_1 = 3 4 agosto
week_2 = nessuno 
week_3 = 15-23 nessuno
week_4 = problemi in una data del 24 o 25

'''

In [11]:
df_2.shape

(689417, 10)

In [20]:
df_4.loc[138698:138715]

,timestamp,CH4,CH4-mgm3,CO2,CO2-mgm3,FLOW,H-AIR,P,T-AIR,T-BOX
138698,08/24/2024 12:38:23.018320,69.0,45.266,52HTTP/1.0 504 Gateway timeout: server respons...,NaN,NaN,NaN,NaN,NaN,NaN
138699,"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 S...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138700,"<html lang=""en"" xml:lang=""en"" xmlns=""http://ww...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138701,<head>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138702,<title>Response denied by WatchGuard HTTP ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138703,"<style type=""text/css"">",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138704,body {,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138705,font-family: Arial,Helvetica,Verdana,Sans-Serif;,NaN,NaN,NaN,NaN,NaN,NaN
138706,font-size: small;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138707,font-weight: normal;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138708,color: #000000;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138709,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138710,div {,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138711,margin-left: auto;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138712,margin-right: auto;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138713,text-align: center;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138714,},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138715,.box {,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
def load_and_clean_csv_moologger(file_path):
    try:
        # Carica il file CSV, impostando tutti i dati come stringhe per evitare problemi di conversione automatica.
        df = pd.read_csv(file_path, skiprows=1)
        print(df.loc[138695:138700])

        # Converte la colonna 'timestamp' da stringa a datetime per facilitare operazioni basate sul tempo.
        df['timestamp'] = pd.to_datetime(df['timestamp'])

        # Definisce un elenco di colonne che dovrebbero contenere valori numerici.
        numeric_columns = ['CH4', 'CH4-mgm3', 'CO2', 'CO2-mgm3', 'FLOW', 'H-AIR', 'P', 'T-AIR', 'T-BOX']

        # Per ogni colonna nell'elenco, tenta di convertire i valori in float. 
        # Qualsiasi valore che non può essere convertito in un numero (ad es., una stringa) viene sostituito con NaN.
        for col in numeric_columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')

        # Rimuove le righe duplicate basandosi sulla colonna 'timestamp' per evitare ridondanze nei dati.
        df = df.drop_duplicates(subset=['timestamp'])

        return df

    except pd.errors.EmptyDataError:
        # Gestisce il caso in cui il file CSV è vuoto o ha una formattazione inaspettata, stampando un messaggio di errore.
        print(f"Il file {file_path} è vuoto o ha una formattazione inaspettata.")
        return pd.DataFrame()
    except Exception as e:
        # Cattura e segnala qualsiasi altro errore incontrato durante il caricamento o la pulizia dei dati.
        print(f"Errore nel caricamento del file {file_path}: {e}")
        return pd.DataFrame()

In [ ]:
#4 settimana strana
#analisi dataframe 4 settimana

In [10]:
combined_df_moologger = pd.concat([df_3, df_4], ignore_index=True)

In [11]:
# Definisce il percorso della cartella contenente i file CSV da processare.
folder_path_moologger = './dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/'

# Inizializza un DataFrame vuoto per combinare i dati di tutti i file CSV.
combined_df_moologger = pd.DataFrame()

# Scorre tutti i file nella cartella specificata, processando solo quelli che terminano con '.csv'.
for file_name in os.listdir(folder_path_moologger):
    if file_name.endswith('.csv'):
        file_path = os.path.join(folder_path_moologger, file_name)
        print(file_path)
        try:
            # Carica e pulisce i dati di ciascun file CSV, poi li combina in un unico DataFrame.
            df_cleaned = load_and_clean_csv_moologger(file_path)
            combined_df_moologger = pd.concat([combined_df_moologger, df_cleaned], ignore_index=True)
        except Exception as e:
            # Segnala eventuali errori incontrati durante il processo di un file specifico.
            print(f"Error processing {file_name}: {e}")

# Rimuove ulteriori righe duplicate nel DataFrame combinato, basandosi ancora sulla colonna 'timestamp'.
combined_df_moologger = combined_df_moologger.drop_duplicates(subset=['timestamp'])

# Salva il DataFrame combinato e pulito in un nuovo file CSV.
output_file_moologger = os.path.join('./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/', 'Combined_MooLogger_agosto.csv')
combined_df_moologger.to_csv(output_file_moologger, index=False)

print("File CSV combinato creato con successo.")

./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/1Settimana_agosto_bufale-08012024000000-08082024235900.csv
                         timestamp   CH4 CH4-mgm3    CO2  CO2-mgm3   FLOW  \
138695  08/06/2024 06:24:29.059279  72.9   47.825  730.6  1315.087  0.826
138696  08/06/2024 06:24:30.062241  88.0   57.731  725.8  1306.447  1.223
138697  08/06/2024 06:24:31.063664  88.6   58.125  726.3  1307.347  0.945
138698  08/06/2024 06:24:32.065230  60.5    39.69  721.1  1297.986  0.626
138699  08/06/2024 06:24:33.067700  82.5   54.123  723.6  1302.487  0.702
138700  08/06/2024 06:24:34.070804  87.8     57.6  725.7  1306.267  1.217

         H-AIR        P   T-AIR   T-BOX
138695  39.291  997.974  35.269  35.052
138696  39.279  998.006  35.269  35.052
138697  39.272  997.958  35.268  35.052
138698  39.272  997.941  35.268  35.052
138699   39.26  997.956  35.268  35.052
138700   39.26  997.984  35.267  35.052
./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/2settimana_agosto_rinna-08092024000000-08162024235900.csv

/tmp/ipykernel_607/2858605126.py:4: DtypeWarning: Columns (1,2,3,4,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, skiprows=1)

                         timestamp   CH4 CH4-mgm3    CO2 CO2-mgm3   FLOW  \
138695  08/10/2024 12:37:22.764827  78.0   51.171  459.9  827.824  0.913
138696  08/10/2024 12:37:23.767588  81.7   53.664  457.6  823.684  0.678
138697  08/10/2024 12:37:24.768376  81.3   53.336  453.2  815.944  0.641
138698  08/10/2024 12:37:25.771052  79.5   52.155  456.5  821.704  0.927
138699  08/10/2024 12:37:26.772855  81.8   53.664  456.7  822.064  0.996
138700  08/10/2024 12:37:27.775403  80.0   52.417  457.5  823.504  0.963

         H-AIR         P   T-AIR   T-BOX
138695  26.515  1004.148  41.404  41.276
138696  26.515  1004.197  41.403  41.276
138697  26.509  1004.251  41.403  41.276
138698  26.503  1004.244  41.403  41.276
138699  26.503  1004.201  41.404  41.276
138700  26.491  1004.156  41.404  41.276
./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/3settimana_agosto_rinna-08162024000000-08232024235900.csv

/tmp/ipykernel_607/2858605126.py:4: DtypeWarning: Columns (1,2,3,4,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, skiprows=1)

                         timestamp   CH4 CH4-mgm3    CO2 CO2-mgm3   FLOW  \
138695  08/17/2024 12:37:22.964958  59.2   38.837  509.9  917.825  0.955
138696  08/17/2024 12:37:23.967632  59.1   38.772  511.1  919.985  0.661
138697  08/17/2024 12:37:24.970744  61.7   40.477  513.3  923.405  0.975
138698  08/17/2024 12:37:25.972225  61.7   40.477  503.5  906.305  1.203
138699  08/17/2024 12:37:26.974603  60.5    39.69  506.4  911.525  0.741
138700  08/17/2024 12:37:27.977345  60.4   39.625  510.0  918.005  1.239

         H-AIR         P   T-AIR   T-BOX
138695   29.14  1000.425  40.585  40.461
138696  29.128  1000.449  40.586  40.461
138697  29.116  1000.506  40.585   40.45
138698  29.103  1000.496  40.585   40.45
138699  29.091   1000.46  40.586   40.45
138700  29.091  1000.424  40.586   40.45
./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/4_settimana_agosto_rinna-08232024000000-08312024235900.csv

/tmp/ipykernel_607/2858605126.py:4: DtypeWarning: Columns (1,2,3,4,6,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, skiprows=1)

                         timestamp   CH4 CH4-mgm3    CO2 CO2-mgm3   FLOW  \
138695  08/24/2024 12:38:20.010242  65.1   42.708  504.5  908.105  1.243
138696  08/24/2024 12:38:21.013161  63.9   41.921  500.5  900.905  0.862
138697  08/24/2024 12:38:22.015774  66.2    43.43  511.0  919.805  0.701
138698  08/24/2024 12:38:23.018320  69.0   45.266  521.7  939.065  0.730
138699  08/24/2024 12:38:24.019436  70.0   45.923  512.0  921.605  0.834
138700  08/24/2024 12:38:25.021559  70.5   46.185  517.3  931.145  1.221

         H-AIR         P   T-AIR   T-BOX
138695  28.322  1003.908   39.75  39.635
138696  28.334  1003.944   39.75  39.635
138697  28.346  1003.965  39.751  39.635
138698  28.353  1003.931  39.752  39.635
138699  28.359  1003.903  39.753  39.635
138700  28.371  1003.927  39.752  39.635
File CSV combinato creato con successo.

In [12]:
df_combined = pd.read_csv('./dati_bufale/dati_grezzi_agosto_luglio/Dataset_CH4/Bufale_Rinna/Agosto/Dati_moologger/Combined_MooLogger_agosto.csv')

In [14]:
df_combined.tail()

,timestamp,CH4,CH4-mgm3,CO2,CO2-mgm3,FLOW,H-AIR,P,T-AIR,T-BOX
2212335,2024-08-30 08:20:42.685681,91.3,59.896,969.1,1741.869,0.619,43.173,1004.007,35.096,35.727
2212336,2024-08-30 08:20:43.688536,82.9,54.385,929.1,1672.388,0.829,43.167,1004.023,35.097,35.727
2212337,2024-08-30 08:20:44.691011,75.1,49.268,873.3,1571.948,1.007,43.167,1004.012,35.097,35.727
2212338,2024-08-30 08:20:45.693816,71.0,46.579,836.3,1505.348,1.221,43.167,1004.003,35.098,35.727
2212339,2024-08-30 08:20:46.695530,64.4,42.249,819.5,1475.107,0.695,43.161,1004.042,35.099,35.737